package org.sweetieslab.model.pancakes;

public enum Ingredient {
  DARK_CHOCOLATE, MILK_CHOCOLATE, WHIPPED_CREAM, STRAWBERRY, BANANA, BLUEBERRY, RASPBERRY,
  CHOCOLATE_CHIP, NUTELLA, PEANUT_BUTTER, MAPLE_SYRUP, HONEY, FLOUR, BAKING_POWDER,
  SUGAR, SALT, EGG, MILK, BUTTER, OIL, HAZELNUT, ALMOND, PECAN, WALNUT, PISTACHIO,

}
